### ISSUE TITLE
Support for cluster-scoped CRDs and namespace-scoped resources in LambdaController

### ISSUE THREAD

**Issue by joelanford** [GoogleCloudPlatform/metacontroller#2] opened 2017-12-16 05:16 UTC
I saw this demo'ed at KubeCon and it gave me some inspiration to try writing a custom LambdaController sync hook.

I'm attempting to watch cluster-scoped custom resources to manage both cluster-scoped and namespace-scoped child resources (for now, namespaces and services). However, for all of the namespace-scoped resources in the returned children array, I get the following error:
```
an empty namespace may not be set during creation
```
I've confirmed that the response coming from my controller contains a namespace for these services, so I'm a bit confused.

Looking through the lambda_controller.go code, it appears that there's a limitation that child resources must be in the same namespace as the parent resource? Just want to confirm if what I'm trying to do is possible.

Thanks!

**Comment by enisoc** [comment] 2017-12-18 19:25
This isn't supported yet, but it's something I plan to add.

Currently, the parent and children have to be in the same namespace. Part of this is because the standard way to express parent-child relationships for k8s API objects ([OwnerReference](https://github.com/kubernetes/community/blob/930ce65595a3f7ce1c49acfac711fee3a25f5670/contributors/design-proposals/api-machinery/garbage-collection.md#api-changes)) doesn't support cluster-scoped or cross-namespace references.

This means we can't rely on the garbage collector to clean up children when the parent goes away, and we can't rely on [ControllerRef](https://github.com/kubernetes/community/blob/930ce65595a3f7ce1c49acfac711fee3a25f5670/contributors/design-proposals/api-machinery/controller-ref.md) to prevent fighting among controllers with overlapping label selectors.

**Comment by marcwickenden** [comment] 2018-06-13 18:31
As requested by @enisoc my use case is automating the deployment of individual namespaces containing various deployments/services + an ingress on a multi-tenant platform. The namespaces come and go and each namespace belongs to a tenant for ease of management. Ideally we could return the namespace JSON (and an ingress-controller deployment) in a hook in response to the generation of a custom resource. Then have all child objects go into the same "parent" namespace. Make sense?

**Comment by joelanford** [comment] 2018-06-13 19:33
This is also my use case. Thanks for describing it so concisely!

**Comment by enisoc** [comment] 2018-06-13 20:46
Thanks for the details. The GC problem mentioned above is still the main blocker as far as I can tell. I haven't seen any indication that the core k8s GC is going to support cluster-scoped or cross-namespace cleanup any time soon, so I'm going to try to think of a way to make this possible without waiting for that.

Just to start some brainstorming:

One potential idea is for Metacontroller to place a finalizer on the parent object so it doesn't disappear immediately when deleted. Since Metacontroller presumably already had a way to decide which child objects it would have sent to your hook, it should know enough to be capable of cleaning those up for you before removing the finalizer.

One limitation of this approach is that it doesn't prevent other controllers from stealing your children, because they would have no ControllerRef (since ControllerRef doesn't allow you to specify cross-namespace references) and would thus look like orphans.

Another option might be for Metacontroller to create "proxy" parent objects in the same namespace as the children. This would prevent the children from looking like orphans. Then when the real parent is deleted, our finalizer will go and delete the proxy parents. Finally, the regular GC will delete the children since the proxy parent is now gone.

@janetkuo @liyinan926 @crimsonfaith91 What do you think?

**Comment by enisoc** [comment] 2018-06-13 21:40
Another idea is a "namespace controller" that lets you create singleton objects in each namespace. We would call your hook once for each namespace, as namespaces are added/updated, and let you return objects to create in that namespace. You could use labels or annotations on the namespaces to decide what to do, if you need extra parameters or if you only want to process certain namespaces.

This would be a more limited pattern, but it bypasses the GC problem discussed above. For the use case that @marcwickenden described, this would mean you directly create the namespace (with whatever annotations you need) instead of creating a cluster-scoped CRD that in turn creates a namespace.

**Comment by marcwickenden** [comment] 2018-06-13 21:55
I nearly wrote this exact idea in Slack! Wasn’t sure if that was deviating from the model too much.

**Comment by crimsonfaith91** [comment] 2018-06-14 05:15
I lean towards creating "proxy" parent objects. As k8s grows, there is possibility for GC to support cross-namespace cleanup in future. We can add an annotation for all created "proxy" parent objects so that we can delete them easily when we have cross-namespace GC. This can be done by 2 steps:
1. use annotation key to identify all "proxy" parents
2. for each parent, update `OwnerReferences` of its children to real parent, which can be found from annotation value in form of `<namespace>/<real-parent-name>`

Namespace controller is a good idea, but if we are adding labels or annotations to decide what to do with the namespaces, it may be easier to do so with the "proxy" parent objects. I don't think we should bypass GC as this involves parent-children relationship.

**Comment by rlguarino** [comment] 2018-07-06 20:52
I did some experiments this morning with cluster scoped owner references on a GKE cluster (1.10.5-gke.0) and it looks like it's working to me. Reading through [this issue](https://github.com/kubernetes/kubernetes/issues/54940) and the [PR that closed it](https://github.com/kubernetes/kubernetes/pull/57211) it looks like Cluster scoped parents should be supported.

I was able to create a create a CluterRoleBinding that references a ClusterRole owner, when I deleted the parent ClusterRole (foreground) the child was removed. When I deleted using `--cascade=true` the owner reference was removed orphaning the child. The same thing happened when I referenced a ClusterRole from a Service in the default namespace.

Parent | Child | Expected Behavior (Deleting parent deletes the child) 
------------ | ------------- | ------------
Cluster | Cluster | :+1:
Cluster | Namespace | :+1: 
Namespace |  Namespace | :+1: 
Namespace | Cluster | :question: (1)
Namespace | Namespace (different) | :question: (2)

So to me it looks like cluster owners should always work, namespaced to namespaced should also work, but I'm not sure how namespaced parents of cluster resources would work..  

WIthout too much magic, I think it would be possible to make ConpositeController/DecoratorController/MapController support look something like the above matrix by merging #62.

(1) I haven't tested this, I don't expect it to make any sense.
(2) I'm not really sure how useful cross-namespace support would be so I've been mostly ignoring the case where both parent and child resources are namespaced and they exist in _different_ namespaces.

**Comment by enisoc** [comment] 2018-07-06 21:32
@rlguarino That's great news! Thanks for the research! Apparently my understanding has been out of date.

I've merged #62. Let's see what else needs to change on the Metacontroller side to make this work.

One problem is that the sync hook API assumes everything is in the same namespace. For example, the `children` map is keyed only by name, not namespace. We'll need to make an API change to support namespaced children for a cluster-scoped parent, since the names might collide across namespaces.

There are also likely other places where we need to relax the assumption that everything is in the same namespace, but that's definitely feasible if the built-in GC supports cluster-scoped OwnerRefs.

**Comment by rlguarino** [comment] 2018-07-07 03:16
Thanks for the extra details, sounds like it should work. I'm going to be
away on vacation for the upcoming week and I'm trying to avoid using my
computer. I should be able to take a stab at this the week after next if
someone doesn't get to it sooner!

--RG

**Comment by enisoc** [comment] 2018-07-11 22:58
@rlguarino It would be awesome if you're able to take a stab when you get back! Please update this thread if you do (or don't) so we can avoid overlap. Also feel free to bug me in the `#metacontroller` channel on Kubernetes Slack if you want to discuss anything synchronously.

**Comment by rlguarino** [comment] 2018-07-19 22:44
Based on our conversation in `#metacontroller` channel on Kubernetes Slack I put together a POC PR #71

**Closed** 2018-09-18 20:04 UTC

**Comment by jianzhangbjz** [comment] 2019-01-05 14:11
Hi, Guys

Just to chime in, I was wondering how to understand the difference between the cluster-scoped and the namespaced CRD. Actually, we can get the Kind that defines by the namespaced CRD across the whole cluster. So, what's the `namespaces-scoped` role？I could not find more details in [CRD](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/).
For example:
```console
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
```
HTTP path:
```console
/apis/stable.example.com/v1/namespaces/*/crontabs/status
```
